This is Glasses. It's a program to aid in computer vision studies. Aid in
vision. Glasses. Get it? Here are the things you need, and the versions I
tested with. (Don't forget the -dev packages!)

sdl     (1.2.12)
sdl-ttf (2.0.9)
g++     (4.1.2, 4.2.0)
GNU make (> 3.81)

It's not tested on anything but linux, but in theory, the staticfile support
should work on OSX.

I'm aiming for some level of cross-platform stuff here, though I don't
particularly care about anything other than g++. Type 'make' to compile. The
makefile uses SECONDEXPANSION, which requires gnu make >= 3.81.

If you have an older make, you can try Makefile.old (make -f Makefile.old). It
just won't be awesome.

